version: '3.6'

services: 
  app:
    build: 
      context: .
      dockerfile: docker/build/Dockerfile
      args:
        # Complete reference https://dockerfile.readthedocs.io/en/latest/content/DockerImages/dockerfiles/php-nginx-dev.html
        - IMAGE=webdevops/php-nginx-dev:8.0
    environment: 
      WEB_ALIAS_DOMAIN: pug-phpday.vm
      WEB_DOCUMENT_ROOT: /app/public
      LOG_STDOUT: /logs/stdout.log
      LOG_STDERR: /logs/stderr.log
      PHP_DATE_TIMEZONE: "Europe/Rome"
    ports:
      - "80:80"
      #- "443:443"
    volumes: 
      - ./app:/app:delegated
      - ./logs:/logs:delegated
    extra_hosts:
      - ${host:-host}:host-gateway

  database:
    image: library/mysql:5.7
    volumes:
    - ./.database:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=cqrs
      - MYSQL_USER=cqrs
      - MYSQL_PASSWORD=cqrs
      - MYSQL_ROOT_PASSWORD=root