framework:
    messenger:
        default_bus: command.bus

        buses:
            command.bus:
                middleware:
                    - doctrine_transaction
            query.bus: ~

        transports:
            sync: 'sync://'
            # async: 'in-memory://'
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            failed: '%env(MESSENGER_TRANSPORT_DSN)%?queue_name=failed'

        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed

#        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        routing:
             'App\Query\User\GetUserQuery': sync
             'App\Query\User\UserWithSameEmailExistsQuery': sync
             'App\Command\User\RegisterUserCommand': async
